/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package January;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Welcome to your January Daily Coding Problems. Use gradle tasks to see your completed problems.");
    }
}
